klr_portrait = [
    'Trapper', 'Wraith',
    'Hillbilly', 'Nurse',
    'Shape', 'Hag',
    'Doctor', 'Huntress',
    'Cannibal', 'Nightmare',
    'Pig', 'Crown',
    'Spirit', 'Legion',
    'Plague', 'Ghost',
]

klr_perk = [
    'BitterMurmur', 'Deerstalker', 'Distressing',
    'HexNoOneEscapesDeath', 'HexThrillOfTheHunt',
    'Insidious', 'IronGrasp', 'MonstrousShrine',
    'SloppyButcher', 'SpiesFromTheShadows',
    'Unrelenting', 'Whispers',
    'UnnervingPresence', 'BrutalStrength', 'Agitation',
    'Predator', 'Bloodhound', 'Shadowborn',
    'Enduring', 'Lightborn', 'Tinkerer',
    'Stridor', 'Thanatophobia', 'ANursesCalling',
    'SaveTheBestForLast', 'PlayWithYourFood', 'DyingLight',
    'HexTheThirdSeal', 'HexRuin', 'HexDevourHope',
    'OverwhelmingPresence', 'MonitorAndAbuse', 'Overcharge',
    'BeastOfPrey', 'TerritorialImperative', 'HexHuntressLullaby',
    'KnockOut', 'BarbecueAndChilli', 'FranklinsDemise',
    'FireUp', 'RememberMe', 'BloodWarden',
    'HangmansTrick', 'Surveillance', 'MakeYourChoice',
    'Bamboozle', 'Coulrophobia', 'PopGoesTheWeasel',
    'SpiritFury', 'HexHauntedGround', 'Rancor',
    'Discordance', 'MadGrit', 'IronMaiden',
    'CorruptIntervention', 'InfectiousFright', 'DarkDevotion',
    'ImAllEars', 'ThrillingTremors', 'FurtiveChase',
    'BlankPerk',
]

klr_addon = [
    [  # Trapper
        'TrapperSack', 'TrapperGloves', 'StrongCoilSpring',
        'PaddedJaws', 'TrapperBag', 'TrapSetters',
        'SerratedJaws', 'LogwoodDye', '4CoilSpringKit',
        'WaxBrick', 'TarBottle', 'SettingTools',
        'SecondaryCoil', 'RustedJaws', 'StitchedBag',
        'OilyCoil', 'honingStone', 'FasteningTools',
        'IridescentStone', 'BloodyCoil',
        'BlankAddon',
    ],
    [  # Wraith
        'TheSerpentSoot', 'TheHoundSoot', 'TheGhostSoot',
        'TheBeastSoot', 'BoneClapper', 'BlinkMud',
        'WindstormMud', 'SwiftHuntMud', 'BlindWarriorMud',
        'WindstormWhite', 'SwiftHuntWhite', 'ShadowDanceWhite',
        'BlinkWhite', 'BlindWarriorWhite', 'WindstormBlood',
        'SwiftHuntBlood', 'ShadowDanceBlood', 'AllSeeingBlood',
        'CoxcombedClapper', 'AllSeeingSpirit',
        'BlankAddon',
    ],
    [  # Hillbilly
        'VegetableOil', 'SparkPlug', 'ChainsawFile',
        'SpikedBoots', 'SpeedLimiter', 'ShopLubricant',
        'PrimerBulb', 'LongGuideBar', 'HomemadeMuffler',
        'GrislyChains', 'DepthGaugeRake', 'DeathEngravings',
        'TheThompsonsMix', 'RustedChains', 'LightChassis',
        'DoomEngravings', 'CarburettorTuningGuide',
        'ThompsonsMoonshine', 'BegrimedChains',
        'BlankAddon',
    ],
    [  # Nurse
        'WoodenHorse', 'WhiteNitComb', 'TornBookmark',
        'MetalSpoon', 'MatchBox', 'BadManKeepsake',
        'PocketWatch', 'DullBracelet', 'DarkCincture',
        'CatatonicBoysTreasure', 'SpasmodicBreath', 'HeavyPanting',
        'FragileWheeze', 'AtaxicRespiration', 'AnxiousGasp',
        'PlaidFlannel', 'KavanaghsLastBreath', 'JennersLastBreath',
        'CampbellsLastBreath', 'BadMansLastBreath',
        'BlankAddon',
    ],
    [  # Shape
        'TackyEarrings', 'BoyfriendsMemo', 'BlondHair',
        'ReflectiveFragment', 'MemorialFlower', 'Jewelry',
        'HairBrush', 'GlassFragment', 'DeadRabbit',
        'MirrorShard', 'JudithsJournal', 'JewelryBox',
        'JMyersMemorial', 'HairBow', 'VanityMirror',
        'TombstonePiece', 'ScratchedMirror', 'LockOfHair',
        'JudithsTombstone', 'FragrantTuftOfHair',
    ],
    [  # Hag
        'RopeNecklet', 'PowderedEggshell', 'DeadFlyMud',
        'BogWater', 'PussyWillowCatkins', 'HalfEggshell',
        'DragonflyWings', 'CypressNecklet', 'BloodiedWater',
        'WillowWreath', 'SwampOrchidNecklet', 'DriedCicada',
        'CrackedTurtleEgg', 'BloodiedMud', 'ScarredHand',
        'RustyShackles', 'GranmasHeart', 'DisfiguredEar',
        'WaterloggedShoe', 'MintRag',
        'BlankAddon',
    ],
    [  # Doctor
        'MouldyElectrode', 'MapleKnight', 'OrderClassI',
        'CalmClassI', 'ScrappedTape', 'PolishedElectrode',
        'InterviewTape', 'RestraintClassII', 'OrderClassII',
        'DisciplineClassII', 'CalmClassII', 'HighStimulusElectrode',
        'RestraintClassIII', 'DisciplineClassIII',
        'RestraintCartersNotes', 'OrderCartersNotes',
        'ObedienceCartersNotes', 'DisciplineCartersNotes',
        'CalmCartersNotes', 'IridescentKing',
        'BlankAddon',
    ],
    [  # Huntress
        'CoarseStone', 'BerusToxin', 'BandagedHaft',
        'AmanitaToxin', 'YewSeedBrew', 'ShinyPin',
        'OakHaft', 'MannaGrassBraid', 'LeatherLoop',
        'FineStone', 'DeerskinGloves', 'YewSeedConcoction',
        'VenomousConcoction', 'RustyHead', 'PungentPhial',
        'FlowerBabushka', 'InfantryBelt', 'GlowingConcoction',
        'BegrimedHead', 'IridescentHead',
        'BlankAddon',
    ],
    [  # Cannibal
        'VegetableOil', 'SparkPlug', 'ChainsawFile',
        'SpeedLimiter', 'ShopLubricant', 'PrimerBulb',
        'LongGuideBar', 'KnifeScratches', 'HomemadeMuffler',
        'GrislyChains', 'DepthGaugeRake', 'Chilli',
        'TheGrease', 'TheBeastsMarks', 'RustedChains',
        'LightChassis', 'CarburettorTuningGuide',
        'BegrimedChains', 'AwardWinningChilli',
        'BlankAddon',
    ],
    [  # Nightmare
        'WoolShirt', 'SheepBlock', 'KidsDrawing',
        'GardenRake', 'PrototypeClaws', 'OutdoorRope',
        'NancysSketch', 'GreenDress', 'CatBlock',
        'UnicornBlock', 'SwingChains', 'NancysMasterpiece',
        'JumpRope', 'BlueDress', 'PillBottle',
        'PaintThinner', 'ClassPhoto', 'ZBlock',
        'RedPaintBrush', 'BlackBox',
        'BlankAddon',
    ],
    [  # Pig
        'WorkshopGrease', 'ShatteredSyringe', 'JohnsMedicalFile',
        'CombatStraps', 'VideoTape', 'UtilityBlades',
        'RazorWires', 'LastWill', 'FaceMask',
        'SlowReleaseToxin', 'RustyAttachments', 'JigsawsAnnotatedPlan',
        'InterlockingRazor', 'BagOfGears', 'TamperedTimer',
        'JigsawsSketch', 'CrateOfGears', 'AmandasSecret',
        'RulesSetNo2', 'AmandasLetter',
        'BlankAddon',
    ],
    [  # Crown
        'SmellyInnerSoles', 'RobinFeather', 'FingerlessParadeGloves',
        'Ether5Vol', 'ThickCorkStopper', 'StickySodaBottle',
        'StarlingFeather', 'SolventJug', 'KeroseneCan',
        'VhsPorn', 'SulphuricAcidVial', 'FlaskOfBleach',
        'Ether10Vol', 'BottleOfChloroform', 'GarishMakeUpKit',
        'Ether15Vol', 'CigarBox', 'CheapGinBottle',
        'TattoosMiddleFinger', 'RedheadsPinkyFinger',
        'BlankAddon',
    ],
    [  # Spirit
        'Zori', 'ShiawaseAmulet', 'OrigamiCrane',
        'GiftedBambooComb', 'WhiteHairRibbon', 'RinsBrokenWatch',
        'MuddySportsDayCap', 'KaiunTalisman', 'JuniperBonsai',
        'RustyFlute', 'KatsumoriTalisman', 'KatanaTsuba',
        'DirtyUwabaki', 'BloodyHairBrooch', 'YakuyokeAmulet',
        'WakizashiSaya', 'PrayerBeadsBracelet', 'DriedCherryBlossom',
        'MotherDaughterRing', 'FathersGlasses',
        'BlankAddon',
    ],
    [  # Legion
        'SmileyFacePin', 'ScratchedRuler', 'MischiefList',
        'FriendshipBracelet', 'NeverSleepPills', 'MuralSketch',
        'JuliesMixTape', 'EtchedRuler', 'DefacedSmileyPin',
        'TheLegionPin', 'SusiesMixTape', 'StolenSketchBook',
        'NastyBlade', 'JoeysMixTape', 'StabWoundsStudy',
        'FranksMixTape', 'FilthyBlade', 'ColdDirt',
        'IridescentButton', 'FumingMixTape',
        'BlankAddon',
    ],
    [  # Plague
        'PrayerTabletFragment', 'OlibanumIncense', 'LimestoneSeal',
        'HealingSalve', 'ProphylacticAmulet', 'PotentTincture',
        'HaematiteSeal', 'EmeticPotion', 'BlessedApple',
        'RubbingOil', 'InfectedEmetic', 'IncensedOintment',
        'ExorcismAmulet', 'AshenApple', 'WorshipTablet',
        'VileEmetic', 'SeveredToe', 'DevoteesAmulet',
        'IridescentSeal', 'BlackIncense',
        'BlankAddon',
    ],
    [  # Ghost
        'Philly', 'WalleyesMatchbook', 'HeadlinesCutouts',
        'CheapCologne', 'TelephotoLens', 'ReusableCinchStraps',
        'OlsensJournal', 'OlsensAddressBook', 'MarkedMap',
        'OlsensWallet', 'LeatherKnifeSheath', 'LastingPerfume',
        'KnifeBeltClip', 'ChewedPen', 'VictimsDetailedRoutine',
        'NightVisionMonocular', 'DropLegKnifeSheath', 'DriversLicense',
        'GhostFaceCaughtOnTape', 'OutdoorSecurityCamera',
        'BlankAddon',
    ],
]

klr_offering = [
    'CoinMinusUC', 'CoinMinusVR',
    'FogReduce', 'FogGainC', 'FogGainUC', 'FogGainVR',
    'HookGainUC', 'HookGainR', 'HookGainVR',
    'BlackWard', 'ShroudOfSeparation',
    'MoriUC', 'MoriR', 'MoriUR',
    'MapMacMillan', 'MapAzarov', 'MapFarm',
    'MapAsylum', 'MapHaddon', 'MapSwamp',
    'MapLery', 'MapRedForest', 'MapSpringWood',
    'MapGideon', 'MapYamaoka', 'MapOrmond',
    'BlankOffering',
]
